cpu: x64: add missing newlines
The compiler doesn't like when you end a file without a newline, inside a comment

jit_prelu_forward.cpp:197:3: error: unterminated comment
  197 | } // namespace dnnl
      |   ^