src: common: back-port mkldnn_getenv from master
GCC9 causing build failure:

recipe-sysroot/usr/include/bits/string_fortified.h:106:34: error: 'char* __builtin_strncpy(char*, const char*, long unsigned int)'
output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
|   106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
|       |

Fixes #483

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
Co-authored-by: Roman Dubtsov <roman.s.dubtsov@intel.com>